window.HIVE_POLICY = {
  "QUARANTINE_SEVERITY": 0.6,
  "TRUST_MIN_SEVERITY": 0.5,
  "TRUST_PER_SEVERITY": 0.3,
  "TRUST_PER_DISAGREE": 0.15,
  "MIN_CONFIDENCE": 0.6,
  "VERIFY_CONFIDENCE": 0.75,
  "GROUNDING_MIN_TRUST": 0.7
};
